### ISSUE TITLE
Implement CI for extension

### ISSUE THREAD

**Issue by palmerj** [linz/postgresql-tableversion#10]
Should implement use of travis CI for this extension

**Comment by palmerj** [comment]
You can run the tests by:

```
sudo make install
make installcheck
```

**Comment by imincik** [comment]
@palmerj , can you please have a look [1] if test output looks OK for you. Thanks

1 - https://travis-ci.org/linz/postgresql-tableversion/jobs/189413772#L357

**Comment by palmerj** [comment]
Thanks @imincik looks good.
