### ISSUE TITLE
debian/control is modified by `make deb`

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#108]
After running `make deb`, `git diff` shows:
```
diff --git a/debian/control b/debian/control
index dab77e5..692d0f8 100644
--- a/debian/control
+++ b/debian/control
@@ -9,6 +9,17 @@ Homepage: http://www.linz.govt.nz
 Vcs-Git: git://github.com/linz/postgresql-tableversion.git
 Vcs-Browser: https://github.com/linz/postgresql-tableversion
 
+Package: postgresql-9.2-tableversion
+Architecture: all
+Depends: ${misc:Depends},
+         postgresql-9.2
+Recommends:
+Description: PostgreSQL table versioning extension, recording row modifications
+ and its history. The extension provides APIs for accessing snapshots of a table
+ at certain revisions and the difference generated between any two given
+ revisions. The extension uses a PL/PgSQL trigger based system to record and
+ provide access to the row revisions
+
 Package: postgresql-9.3-tableversion
 Architecture: all
 Depends: ${misc:Depends},
```

Basically a section for PostgreSQL 9.2 is added.

I'd like to drop debian/control completely but @imincik reports doing so might break some workflows (automated package building on some systems, see #105)

**Comment by imincik** [comment]
@strk , solution for that is to update `debian/pgversions` file to contain `9.3+`

**Comment by imincik** [comment]
PR #112 created

**Comment by strk** [comment]
I'm reopening this issue because this is happening again now that PostgreSQL 10 package is out.
Our generated debian/control only contains up to PostgreSQL 9.6 and debian/pgversion only restricts to 9.3+ which includes 10 (now, and only now).

I still think we should drop debian/control anyway I'm open to other suggestions @imincik

**Comment by imincik** [comment]
We just need to update https://github.com/linz/postgresql-tableversion/blob/master/debian/pgversions file to  support only 9.3-9.6

**Comment by imincik** [comment]
Or it is as well possible to set it via variables

```
$ export PG_SUPPORTED_VERSIONS="9.3 9.4 9.5 9.6"
$ export DEB_PG_SUPPORTED_VERSIONS=$PG_SUPPORTED_VERSIONS
```

**Comment by strk** [comment]
> We just need to update https://github.com/linz/postgresql-tableversion/blob/master/debian/pgversions file to  support only 9.3-9.6

Done in https://github.com/linz/postgresql-tableversion/pull/126,
please approve

**Comment by strk** [comment]
Reopening for backport to 1.4

**Comment by strk** [comment]
Backported via https://github.com/linz/postgresql-tableversion/pull/127
