### ISSUE TITLE
Table versioning data corruption (Related to #87)

### ISSUE THREAD

**Issue by SPlanzer** [linz/postgresql-tableversion#115]
This has arisen as part of /linz/ds-dev-team/issues/46, a task to test all data fixes for /linz/AIMS/issues/293 but is specifically related to data/bug fix #87 

After executing #87 there are still instances where _revision_created > _revision_expired. 

```
SELECT
  _revision_created,
  _revision_expired,
  id, 
  --distinct(id)
  status
FROM 
  table_version.bde_crs_parcel_revision
WHERE 
  _revision_created > _revision_expired
ORDER BY _revision_created;

```
| _revision_created | _revision_expired | id |status|
|----|----|----|----|
|10547|9748|3849466|"CURR"|
|10547|9748|4952264|"CURR"|
|10547|9748|4074499|"CURR"|
|10489|9748|7865789|"PEND"|
|10068|9748|7853652|"APPR"|
|10489|9748|7865791|"PEND"|
|10489|9748|7865792|"PEND"|
|10617|9748|6730533|"HIST"|
|10489|9748|7865793|"PEND"|
|10068|9748|3078900|"CURR"|

This is related to the bug ver_fix_revision_disorder() whereby as seen below both updates are identical. The second update should be updating _revision_expired rather than _revision_created.

https://github.com/linz/postgresql-tableversion/blob/5e0c9ef583b9a2a2b1ec32aa799c145d6d9771ee/sql/17-fix_revision_disorder.sql#L39-L48

This has left us with the "table_version.%s_%s_revision" tables having the _revision_created ids correctly order as per the fix but no fix being applied to the _revision_expired ids. As the the ver_fix_revision_disorder() function "tidies" up the the table_version.revision ids there are no reference to the affected  _revision_expired ids that were not 're-ordered' in the table_version.revision table any longer.

https://github.com/linz/postgresql-tableversion/blob/5e0c9ef583b9a2a2b1ec32aa799c145d6d9771ee/sql/17-fix_revision_disorder.sql#L133

Therefore:
From the above table the _revision_expired id 9748 does not exist in the  table_version.revision table

```
SELECT 
  id, 
 revision_time, 
 start_time, 
 user_name, 
 schema_change, 
 comment
  FROM table_version.revision
  WHERE id = 9748

Returns > 0 Rows
```

**FROM HERE**
This fix/bug has been applied on AIMS prod and data is corrupt! This is stop the addressing them from performing road edits (linz/AIMS/issues/297)

I will add to this issue and document those records affected below.

Ideally we need to know the mappings of those _revision_created ids that were modified as part of ver_fix_revision_disorder() and this mapping could be applied to the _revision_expired ids.

failing this we may need to take a more approximated approach using dates to ensure that the _revision_expired ids are in order and greater than _revision_created ids. This date range could possibly come from LDS change sets

**Comment by dwsilk** [comment]
Also note that there were tests for this functionality but the operators are the wrong way around, so they are testing the exact opposite of what is required:

https://github.com/linz/postgresql-tableversion/blob/master/test/sql/base.pg#L630-L638

The greater than / less than operators should be switched on those two tests.

**Comment by palmerj** [comment]
Ops. Is there a way we can reverse this corruption? Did we log what rows changed, or have a back-up before and after? 

Maybe to help @strk who I think is back tomorrow for work, we could load the data into li-experimental. if it's not already there..?

**Comment by palmerj** [comment]
cc @imincik

**Comment by imincik** [comment]
Yes, @strk is back to work tomorrow

**Comment by SPlanzer** [comment]
436 records across all versioned tables whereby  _revision_created > _revision_expired.

queried via this [function](https://gist.github.com/SPlanzer/67852efb8e99084339d1cc90e13b378a)


[created_grater-than_expired.txt](https://github.com/linz/postgresql-tableversion/files/1962944/created_grater-than_expired.txt)

**Comment by SPlanzer** [comment]
> Ops. Is there a way we can reverse this corruption? Did we log what rows changed, or have a back-up before and after?

looking into it

>Maybe to help @strk who I think is back tomorrow for work, we could load the data into li-experimental. if it's not already there..?

instance of AIMS on the li-server with current AIMS prd data. This only has the AIMS required table versioning. Though this will be enough to start with

Database's ports can be forwarded as below. 

```
ssh -N -L 15432:localhost:15432 linz-experimental

user:pw == vagrant:vagrant
This assumes you have and entry for  'linz-experimental' in your ssh config
```

**Comment by palmerj** [comment]
Thanks @SPlanzer

**Comment by SPlanzer** [comment]
I am currently restoring an old back up from the 9th Feb to explore a solution. 

The idea would be:
* Test how many of the problematic 436 version ids are in the 9 Feb back up.
* Use the metadata (revision_time, start_time, user_name, schema_change, comment) of those records in the 9 Feb data to match with the new ids in the current prd data. This will provide a mapping of pre and post fix revision ids. 
* Use this mapping to update the _revision_expired ids in the table_version.<schema>_<table>_revision tables that no longer exist in the  table_version.revision table for prd data.
* If it is only a small amount 436 records we can not match in the  9 Feb backup, these can be hacked in to order. That is, Those records can be attributed ids that conform to the order of the records that do have a mapping from 9 Feb to current prd data.
 
This is going to take time as the 9Feb data must placed on the LI -Server. network speeds means this takes up to 6 hrs (using corp network and physically copying onto server.). All going well this data will be installed into an AIMS instance by the end of today.

**Comment by SPlanzer** [comment]
9th Feb back up max id was 8857

**Comment by strk** [comment]
Thanks @billgeo for the catch of the bug in test, and thanks @SPlanzer for noticing the problem with _revision_expired not being updated. A fix for master branch is in #116 (both for test and implementation). I'm going to try the fix on the LI server and ask you all to give the new code a try before I backport to branches 1.4 and 1.3

**Comment by strk** [comment]
A query to find rows in which `_revision_expired` referenced an unknown revision:
```
SELECT * FROM table_version.public_t_revision where _revision_expired not in ( select _revision_created from table_version.public_t_revision );
```

There should be no further corruption as the sequence used to assign new revisions would be incremented as the first thing done by `ver_fix_revision_disorder` so theoretically fixing things would be a matter of finding out the mapping between old values and new values. Such mapping should have been emitted as a NOTICE by the call to `ver_fix_revision_disorder` call. Any chance to have such NOTICE output ?

**Comment by strk** [comment]
@SPlanzer which database name is the Feb9 restore ? I see `aims_dev_20180502144752`, `aims_dev` and `aims` via port 2201...

**Comment by SPlanzer** [comment]
for reference. Mostly timestamp reference

```
./postgresql-9.3-main.log:2018-05-01 15:42:25 NZST:144.66.43.25(50889):splanzer@linz_db:[46329]:[pgAdmin III - Query Tool]: WARNING:  Spurious record in table_version.versioned_tables for table TEMP_meshblock_concordance in schema admin_bdys: table_version.admin_bdys_TEMP_meshblock_concordance_revision does not exist)
./postgresql-9.3-main.log.1:2018-04-27 14:51:29 NZST:144.66.43.34(50404):splanzer@linz_db:[23239]:[pgAdmin III - Query Tool]: WARNING:  Spurious record in table_version.versioned_tables for table TEMP_meshblock_concordance in schema admin_bdys: table_version.admin_bdys_TEMP_meshblock_concordance_revision does not exist)

```

**Comment by SPlanzer** [comment]
Database backup to be requested from DataCom from prior to incident to obtain mappings from

**Comment by strk** [comment]
So plan B: write a function which gives for each versioned table
a list records where the "_revision_expired" value is not in
table_version.revision. Full records.

Then we'll use those full records to find a match (via table-name,
primary key and _revision_created) on the backup database.

Does it sound like something that could work ?

I wonder if we could do this in a single function via dblink (or
more modern equivalent).

**Comment by SPlanzer** [comment]
> Does it sound like something that could work ?

That is what we are planning on using the backups for

**Comment by SPlanzer** [comment]
@strk in response to your query about the data currently on the LI-server  (server over 2201). This is 
2018-02-12 10:47:37 7578625084 aims_20180209000000.tar.gz
as stored in the linz-aims-data s3 bucket. 

I also have have this on the li-server (/home/splanzer/aims2/AIMS-deployment/data)

Please let me know if you require any data refreshes. I am happy to rebuild this

**Comment by SPlanzer** [comment]
> Hi Simon
>
>I need to keep Tania and Tim up-to-date with this issue.
>
>I can read the commentary, and see you are all hard at work (thanks!!) but for expedience, and to be sure I say the right stuff, can you give me a few brief bullet points as to:
>
> - If a fix has been found – what this is
>
> - When it may be in production so Addressing team can do their thing, and LINZ clients see the new datasets
>
> Cheers
>
> Echo

Hi @ebrookewhite I have moved your email here for transparency. This way others can follow the conversation and importantly add to any remarks I make.  

> - If a fix has been found – what this is

The fix is going to require obtaining a full back up from datacom of the database prior to the corruption. We will then be able to use the revision metadata in the back up to create a mapping, mapping ids post/pre corruption. The Ids in the revision tables (e.g. table_version.bde_crs_parcel_revision) that do not related to a table_version.revision id will then be updated based on this mapping via a function we will need to produce to do just that. 

> -  When it may be in production so Addressing team can do their thing, and LINZ clients see the new datasets

The first step will be standing up the database back up. I  am completely unsure how long it will take to get a back up from datacom and restore this. @jrlinz is doing this because (I think) he has experience with datacom getting these back ups. @jrlinz any ideas how long this will take. 


I will bullet point next steps in a comment below

**Comment by SPlanzer** [comment]
fyi @ebrookewhite , @dwsilk , @jrlinz, @strk 

Next steps:
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by strk** [comment]
Please remember that this is a _public_ repository.
I'll be spending today on the "write a function to map ids between backup and prd data" item. Still unsure about how to do that...

**Comment by strk** [comment]
With all PRs fixing the bug I think this ticket can be closed.
I don't see a way to fix the corruption produced by running the bogus function w/out having access to backups or similar other external data so I don't think there's anything more to do in this repository, other than releasing ASAP a bugfix release for 1.4 and 1.3 branches.

**Comment by SPlanzer** [comment]
> With all PRs fixing the bug I think this ticket can be closed.

@strk this ticket has become a beast. In retrospect it should have been split into tickets addressing source code updates and data fixes. 

Id prefer to keep this open to track the data update as we have a number of people watching this, with the provision of being more aware of breaking issues down in the future.

**Comment by SPlanzer** [comment]
Still awaiting backups from datacom. This is being manager via help desk ticket 7217921

**Comment by SPlanzer** [comment]
@jrlinz has reminded datacom of their obligations around getting backups to us and escalated this issue with the Datacom SMD to increase priority 

Thanks @jrlinz

**Comment by strk** [comment]
do you agree about closing this issue ? The bug in ver_fix_revision_disorder was addressed by pull requests #116 #117 and #118 (for master, 1.4 and 1.3 branches, all merged)

**Comment by strk** [comment]
@SPlanzer sorry I read your reply just now. I think data fixes should be discussed in a private repository, not here... Can you ping all watchers from a private ticket ?

**Comment by SPlanzer** [comment]
As per the above comment this conversation will now continue @ linz/ds-dev-team/issues/76.

Closed

**Comment by SPlanzer** [comment]
Testing Envi

1. Stand up aims via ansible deployment -[ ]
1.1 increase disksize
2. Dump/Restore full data set (using all proven [method in master](https://github.com/linz/AIMS-deployment/blob/master/utils/aims_dump.sh))
3. dump retore table version
