### ISSUE TITLE
Package 1.3.3 and 1.4.3 releases

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#119]
Both were tagged to fix the bug in `ver_fix_revision_disorder`.
See https://github.com/linz/postgresql-tableversion/releases/tag/1.3.3 and https://github.com/linz/postgresql-tableversion/releases/tag/1.4.3

**Comment by imincik** [comment]
@strk , only latest package version can go to repository. If we need 1.3.3, I can build deb and upload it somewhere.

**Comment by imincik** [comment]
1.4.3 package uploaded to `test` branch
