### ISSUE TITLE
Example does not work as expected

### ISSUE THREAD

**Issue by jachym** [linz/postgresql-tableversion#12]
Hi,
trying to reproduce example described in docs/table_version.md, the last step did not work for me

```
=# SELECT * FROM table_version.ver_get_foo_bar_diff(1001, 1002);
```

I get
```
┌──────────────┬────┬─────┐
│ _diff_action │ id │ baz │
├──────────────┼────┼─────┤
└──────────────┴────┴─────┘
(0 rows)
```
Maybe I'm missing something? in the example: you are just creating the first revision (1001), finishing it (`SELECT table_version.ver_complete_revision();`) but not creating new one (1002)? Therefore the diff will not make sense?

NOTE: I did not go through the whole documentation yet, so maybe I'm really missing something, this is just the first touch with table_version for me

**Comment by imincik** [comment]
Yes, you are right. Revision  1002 doesn't exist. We need to update docs.

**Comment by palmerj** [comment]
Fixed in add1e92

**Comment by jachym** [comment]
Well, I'm working on the document a bit, expect pullrequest soon
https://github.com/jachym/postgresql-tableversion/blob/master/doc/table_version.md

**Comment by palmerj** [comment]
Great thanks. It's never had a review so that's great. Watch that formatting in the synopsis though.

**Comment by jachym** [comment]
ee, fixed ;-)
