### ISSUE TITLE
table_version.ver_enable_versioning(schema, table) should accept just one parameter

### ISSUE THREAD

**Issue by jachym** [linz/postgresql-tableversion#13]
I do not much about SQL, but having `ver_enable_versioning()` accepting just one parametr (`schema.table`, or just `table` from default schema) would be more convenient (?)

**Comment by imincik** [comment]
Do you mean having "schema" and "table" information as one parameter instead having two ? If yes, it is common practice to have this information in separate parameters - see for example PostGIS AddGeometryColumn [1].

Leaving "schema" as optional can be implemented, but I see some problems and very small benefits it can bring. 

1 - http://postgis.net/docs/AddGeometryColumn.html

**Comment by strk** [comment]
Best approach nowadays is probably taking a `regclass` type, which is a builtin type allowing you to specify the table path as a string, either fully qualified or not (in which case `search_path` is used).

The `AddGeometryColumn` function from `PostGIS` predates availability of such builtin of `PostgreSQL` and it has an interface which is specified in an `OGC` standard.

I think this could be done before next release, there's no need to drop old interface, but we can add another (and the old can become a wrapper).

`regclass` exists at least as of PostgreSQL 7.x, so we're safe: https://www.postgresql.org/docs/7.4/static/datatype-oid.html

**Comment by strk** [comment]
I gave this a try,and have a patch working for `enable_versioning`, but then I guess you'd also want `disable_verisoning`, and then `is_vesioned` and friends, so maybe this is better to postpone to 1.4.0

**Comment by imincik** [comment]
@strk , this is request from external contributor, not too much agreed. So leave it for now.
