### ISSUE TITLE
[1.5.0] table_version-1.5.0.sql.tpl is installed into the wrong directory 

### ISSUE THREAD

**Issue by tuxmaster5000** [linz/postgresql-tableversion#144]
Build it with pgsql 11 under CentOS 7 this this file will installed under /usr/pgsql-11/bin/share/table_version but this path is the wrong one.
It must installed under /usr/pgsql-11/share/extension/

**Comment by tuxmaster5000** [comment]
The same will happens build it for pgsql 10.

**Comment by strk** [comment]
It's by design, see https://github.com/linz/postgresql-tableversion/issues/143#issuecomment-431776066

**Comment by strk** [comment]
It's by design, see https://github.com/linz/postgresql-tableversion/issues/143#issuecomment-431776066
