### ISSUE TITLE
Publish Debian packages for PostgreSQL 10/11

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#165]
Should be possible after merging #164

Even better would be starting to provide postgresql-agnostic packages too (see #95)

**Comment by strk** [comment]
This is now ready to go @imincik and is blocking testing of PostgreSQL 10 for bde-processor-deployment: https://github.com/linz/bde-processor-deployment/pull/364

**Comment by imincik** [comment]
Packages pushed to Packagecloud test branch.
