### ISSUE TITLE
Release version 1.7.0

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#176]
For improved/fixed upgradeablility and schema loader verbosity

**Comment by imincik** [comment]
If this is needed, we need to release package this week. /cc @strk

**Comment by strk** [comment]
Not really need, unless we install dev versions in production.

See detailed changes here: https://github.com/linz/postgresql-tableversion/blob/3f29dd5841717aa4516487d072cc2d005a17c73a/CHANGELOG.md#170dev---2019-mm-dd

**Comment by strk** [comment]
We now have security model review that would be part of 1.7.0 (for `ver_complete_revision` and `ver_delete_revision`)

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
Still relevant

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
@strk , are we still planning to release 1.7.0 for BDE Processor release 1.1. If yes, we need to do it this week, if not, we have to move this task to backlog.

**Comment by strk** [comment]
Moved to Backlog and BDE Release 2.0

**Comment by strk** [comment]
Release tagged: https://github.com/linz/postgresql-tableversion/releases/tag/1.7.0
Ready for package: #189
