### ISSUE TITLE
Review security model of table_version.ver_delete_revision

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#178]
At the moment the function runs with the permissions of the invoker, which would ideally not have direct access to drop tables under `table_version` (revision tables). Note that the `ver_create_revision` does instead run with the permissions of the definer, giving anyone the ability to create revisions. So current situation is that someone can create a revision but not delete it afterwards. Not sure this is what we want.

**Comment by strk** [comment]
NOTE: this scenario is documented as possible in the current doc/table_version.md file (that only the owner of `table_version` extension/schema can delete unused revisions

**Comment by palmerj** [comment]
> NOTE: this scenario is documented as possible in the current doc/table_version.md file (that only the owner of table_version extension/schema can delete unused revisions

This make sense to me.

**Comment by strk** [comment]
See if you like #181 -- sounds cleaner to me

**Comment by strk** [comment]
@palmerj I just also noticed that you can actually DELETE a revision which is in progress, isn't that to be forbidden ?

**Comment by strk** [comment]
I've pushed a fix, in #181, to also forbid deleting in-progress revisions
