### ISSUE TITLE
Review if deleting a column from versioned table should be allowed

### ISSUE THREAD

**Issue by palmerj** [linz/postgresql-tableversion#18]

**Comment by billgeo** [comment]
What's the proposal here? BDE did delete a column recently which needs to be handled somehow.

**Comment by palmerj** [comment]
No proposal yet. Needs to be reviewed. But deleting is really bad. We will obvoiusly need to deal with the past.

**Comment by imincik** [comment]
Deleting columns from database is bad practice. Maybe we can maintain
another metadata table where we will store current columns list for every
revision and delete column function will just remove column from metadata
table.

But maybe we can also consider potential problems with support of renaming
columns.
Is there any way how to rather work with some column id (oid) rather then
with actual column name?

**Comment by palmerj** [comment]
Recording list of columns per revision is what I was thinking, and could easily fit in with #11.

My view is rename should be more simply treated as delete and then add. The reason being is the versioning data model becomes much more complex. Plus I haven't seen a linz situation for this yet. Like with delete it's pretty bad practice that a column gets renamed after it goes to production, especially for public facing columns. The only delete column we've had so far at least wasn't for a public facing column (was an internal column that we loaded and filtered out in the public full bde generation and didn't use internally).

**Comment by imincik** [comment]
This task is still relevant.

**Comment by palmerj** [comment]
This task is still relevant.

**Comment by palmerj** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.
