### ISSUE TITLE
Publish packages for Ubuntu Bionic distribution

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#183]
Tested to work with #182

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
As I just did package for [linz-bde-uploader](https://github.com/linz/linz-bde-uploader/issues/207) I'm thinking I could try this myself, ok with you @palmerj  ?
Would unblock https://github.com/linz/linz-lds-bde-schema/pull/141

**Comment by strk** [comment]
```
Pushing build-area/postgresql-11-tableversion_1.7.1-1linz~bionic1_all.deb... success!
Pushing build-area/postgresql-9.4-tableversion_1.7.1-1linz~bionic1_all.deb... success!
Pushing build-area/postgresql-9.5-tableversion_1.7.1-1linz~bionic1_all.deb... success!
Pushing build-area/postgresql-9.6-tableversion_1.7.1-1linz~bionic1_all.deb... success!
Pushing build-area/postgresql-10-tableversion_1.7.1-1linz~bionic1_all.deb... success!
```

**Comment by strk** [comment]
For the record: these are the warnings coming out from `deb-build-binary --git-tag`:
```
W: postgresql-10-tableversion: latest-debian-changelog-entry-without-new-version
W: postgresql-10-tableversion: priority-extra-is-replaced-by-priority-optional
W: postgresql-10-tableversion: binary-without-manpage usr/bin/table_version-loader
```

(3 warnings for each target PostgreSQL version)

**Comment by strk** [comment]
Reopening until we promote to production

**Comment by imincik** [comment]
@strk , we are promoting packages from `test` repo branch to `prod` after BDE Processor UAT is done (https://github.com/linz/bde-processor-deployment/wiki/Production-Deployment#production-deployment). I think we don't need this ticket. Will close it.

**Comment by strk** [comment]
@imincik I just stumbled upon the need of that bionic package in production, for this:
https://github.com/linz/bde_test_dataset/pull/30/checks?check_run_id=330953358#step:4:94

Shall we have github-actions test against the _test_ repo instead of prod ?
