### ISSUE TITLE
Document which Ubuntu version we support in the apt repository

### ISSUE THREAD

**Issue by palmerj** [linz/postgresql-tableversion#184]

**Comment by strk** [comment]
@imincik I think you know this better than me as it relates to
packaging

**Comment by dwsilk** [comment]
Reopening - this tripped us up.

**Comment by palmerj** [comment]
Note we support PG 9.4 - PG 11. 

We are only supporting trusty (14.04) at the moment. Bionic (18.04) is coming, and will likely be published in the next month or so as we upgrade components. See https://packagecloud.io/app/linz/prod/search?q=tableversion

Note Bionic packaging is in test https://packagecloud.io/app/linz/test/search?q=tableversion
