### ISSUE TITLE
Review the allowable column datatype changes that should be allowed

### ISSUE THREAD

**Issue by palmerj** [linz/postgresql-tableversion#19]
At the moment any change that PostgreSQL can handle are allowed: https://github.com/linz/postgresql-tableversion/blob/master/sql/09-table_change_column_type.sql#L2

**Comment by imincik** [comment]
This task is still relevant.

**Comment by palmerj** [comment]
This task is still relevant.

**Comment by palmerj** [comment]
This task is still relevant.
