### ISSUE TITLE
Debian packaging problem

### ISSUE THREAD

**Issue by imincik** [linz/postgresql-tableversion#191]
BDE Processor Deployment is reporting packaging issue:

```
dpkg-buildpackage: source package postgresql-tableversion
dpkg-buildpackage: source version 1.7.0-1linz~trusty1
dpkg-buildpackage: source distribution trusty
dpkg-buildpackage: source changed by Ivan Mincik <imincik@linz.govt.nz>
 dpkg-source --before-build postgresql-tableversion
dpkg-buildpackage: host architecture amd64
dpkg-source: error: postgresql-tableversion/debian/control doesn't list any binary package
dpkg-buildpackage: error: dpkg-source --before-build postgresql-tableversion gave error exit status 255
The command "OK=1; for ROLE in $ROLES; do ansible-playbook -i inventory/localhost --connection=local --extra-vars " $EXTRA_ANSIBLE_VARS PRODUCT_NAME=travis ROLE_NAME=$ROLE DB_PSQL_VERSION=$DB_PSQL_VERSION BDE_PSQL_VERSION=$DB_PSQL_VERSION DB_PGIS_VERSION=$DB_PGIS_VERSION " --vault-password-file=ansible-password.txt deployment/$ROLE-deploy.yml || { OK=0 && break; }; if test "$ROLE" = "bde-processor" -a "$BDE_BRANCH" != "none"; then sudo bash utils/update-from-branch.sh $BDE_BRANCH $DB_PSQL_VERSION || { OK=0 && break; }; fi; done; test $OK = 1" exited with 1.
```

See: https://travis-ci.com/linz/bde-processor-deployment/jobs/220135398#L3597

**Comment by strk** [comment]
Seems to only happen for PostgreSQL 9.3, is this right ?

**Comment by imincik** [comment]
just investigating

**Comment by imincik** [comment]
ah, @strk you just dropped 9.3 from Travis testing. Let's see if it helps.

**Comment by strk** [comment]
I only removed it from the Travis configuration of postgresql-tableversion but the problem seems to surface in testing of bde-processor-deployment testing as well, suggesting this may be a problem elsewhere. Anyway, for _this_ repository, the problem was fixed by that (maybe this ticket was filed in the wrong repo?)

**Comment by imincik** [comment]
Issue moved to [linz/bde-processor-deployment #597](https://github.com/linz/bde-processor-deployment/issues/597) via [**ZenHub**](https://www.zenhub.com/)
