### ISSUE TITLE
TRUNCATE is not handled by revision trigger

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#204]
A table that cannot be edited using DELETE/INSERT/UPDATE without starting a revision can still be TRUNCATED. It sounds inconsistent to me. I think the trigger should fire on TRUNCATE as well (eventually forbidden if it cannot be handled cleanly).

Do you agree @palmerj ?

**Comment by palmerj** [comment]
Yes good idea to handle TRUNCATED, and to raise a not support exception

**Comment by imincik** [comment]
Yes, I agree with what @palmerj is saying.

**Comment by strk** [comment]
Not supported means you'd not be able to TRUNCATE a versioned table. Why not handle TRUNCATE the same as DELETE all rows ?

**Comment by strk** [comment]
PR #205 goes the UNSUPPORTED way...
