### ISSUE TITLE
Permission Errors on _changeset_revision

### ISSUE THREAD

**Issue by josephramsay** [linz/postgresql-tableversion#21]
@jason-bedford reported a failure using the AdminBoundaries updater with the error message.
```
Error: permission denied for relation _changeset_revision
CONTEXT: PL/pgSQL function table_version._ver_apply_inc_delete(regclass,name,name) line 3 at RETURN
PL/pgSQL function table_version._ver_apply_changes(regclass,regclass,name,name) line 26 at assignment
SQL statement "SELECT * FROM table_version._ver_apply_changes(
p_original_table, p_new_table, 'table_diff', p_key_column
)"
```

**Comment by josephramsay** [comment]
Have implemented a temp fix on prd1 by:
1. Adding
`GRANT ALL ON _changeset_revision TO PUBLIC;`
to the table_version.ver_create_revision function
2. Changing the permissions on tables_changed from/to
```
--GRANT SELECT ON TABLE table_version.tables_changed TO public;
GRANT ALL ON TABLE table_version.tables_changed TO public;
```
Since there is probably some other underlying problem causing this failure I won't submit a PR for this change until further investigation

**Comment by palmerj** [comment]
@jrlinz I think this looks like you haven't applied the correct permissions to the '_changeset' table. When table is versioned for the first time the permissions are copied from source table to revision history table. See:

https://github.com/linz/postgresql-tableversion/blob/master/sql/01-enable_versioning.sql#L84

However there was a small issue for public permissions not being replicated until 640ac01 in version 1.2.0, so maybe that's what your issues relates to. If so then please upgrade to 1.2 and then manually apply the fix.

**Comment by jrlinz** [comment]
This happened after the adminboundaries updater was run on prd2. the table has been there for a while. Its likely versioning for the original meshblock table wasn't set up correctly. There have been lots of other discrepancies with this data. Thx for the advice, I'll look at the version and _changset table.
