### ISSUE TITLE
Publish postgresql-agnostic packages

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#212]
Now that it is [possible](https://github.com/linz/postgresql-tableversion/issues/210) to have them.

**Comment by strk** [comment]
It has to be decided if we want to publish 1.8.0 packages with this change, or wait for 1.9.0 to do that.
Changes are _only_ in the debian packaging, not in any installed file.
Opinions @imincik ?

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
Replaced by #213
