### ISSUE TITLE
Publish new package of version 1.8.0, with dropped PostgreSQL dependency

### ISSUE THREAD

**Issue by imincik** [linz/postgresql-tableversion#213]
Package new version containing package without PostgreSQL dependency.

**Comment by strk** [comment]
There's no new version of the code, only a new packaging. I checked. No change in release-1.8 and master other than the packaging change. I guess I should backport those changes to the 1.8 branch, do you agree @imincik ? If so please file a ticket for that task if you want me to do it ?

**Comment by strk** [comment]
This was a duplicate of #212, btw...

**Comment by imincik** [comment]
Packaged and uploaded to `test` branch.
