### ISSUE TITLE
Publish new debian packages for 1.8.0

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#217]
With the duplicated loader fix in PR #215

**Comment by strk** [comment]
@imincik can you confirm the version of the new packages you installed ?
Ideally with a full version / link to the packages, in this ticket (close it as needed, as issues dependencies are in place)

**Comment by imincik** [comment]
@strk , we have now following versions in `test`:
* https://packagecloud.io/linz/test/packages/ubuntu/bionic/tableversion_1.8.0-3linz~bionic1_all.deb
* https://packagecloud.io/linz/test/packages/ubuntu/bionic/postgresql-10-tableversion_1.8.0-3linz~bionic1_all.deb

**Comment by strk** [comment]
@imincik thepackage for PostgreSQL 9.4 is missing here: 
https://packagecloud.io/app/linz/prod/search?q=tableversion_1.8.0-3&filter=all&filter=all&dist=

**Comment by imincik** [comment]
PG 9.4 is EOL since February 13, 2020, so I believe our packaging process can't build packages for it now.

**Comment by imincik** [comment]
And nobody at LINZ is using this version.

**Comment by strk** [comment]
Ok then I'll drop < 9.6 version testing from master branch of linz-bde-schema
