### ISSUE TITLE
Deb package for Postgres 12 and 13.

### ISSUE THREAD

**Issue by diegoagudo** [linz/postgresql-tableversion#227]
Do you have any plans to release a package for postgres 12 and 13?

**Comment by l0b0** [comment]
We would like to release for versions 12, 13, and 14, all of which are [currently supported](https://www.postgresql.org/support/versioning/).

**Comment by l0b0** [comment]
High estimate if I have to do it, because I'm not familiar with this repo or the relevant Postgres internals.

**Comment by l0b0** [comment]
[PostgreSQL 12 is supported](https://github.com/linz/postgresql-tableversion/pull/238)

**Comment by l0b0** [comment]
We're progressing on PostgreSQL [13](https://github.com/linz/postgresql-tableversion/pull/239) and [14](https://github.com/linz/postgresql-tableversion/pull/240) as well.
