### ISSUE TITLE
Provide debian packages for more PostgreSQL versions ?

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#27]
I noticed that `debian/control` is only for building the extension against PostgreSQL 9.3.
It might be useful to generalize the configuration to allow building against multiple versions.
Travis is testing the extension against PostgreSQL versions from 9.2 to 9.6 and both build and usage is successful there.

See also #26 which is about adding package generation to the Travis config.

\cc @imincik

**Comment by imincik** [comment]
I agree, we should support also other PostgreSQL versions.

**Comment by strk** [comment]
I'm reopening this because the packages built with documented procedure (and current Travis) are still all broken so are not yet addressing the multiple-PostgreSQL version

**Comment by imincik** [comment]
Packaging for multiple versions pushed to `master` and `release-1.3` branches.

Good to read `man pg_buildext` and `/usr/share/postgresql-common/supported-versions` before use.
