### ISSUE TITLE
Debian source package build fails

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#29]
the README recipe for [building the debian package](https://github.com/linz/postgresql-tableversion/blob/master/README.md#building-debian-packaging) fails on my machine with the message:

> dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../postgresql-tableversion_1.2.0.orig.tar.{bz2,gz,lzma,xz}

Adding the `-b` switch (binary-only) fixes the generation of tarball.

**Comment by strk** [comment]
I'm reopening this because source packages building is still not documented in README file

**Comment by imincik** [comment]
@strk , I don't think Debian packaging should be documented for every project. 

We have Debian packaging docs here: https://github.com/linz/linz-software-repository/wiki/Debian-packaging
