### ISSUE TITLE
Easy Installation method is out of date

### ISSUE THREAD

**Issue by dwsilk** [linz/postgresql-tableversion#30]
The **Easy Installation** method documented in the README installs `1.1.1`, latest version is `1.2.0`. Not sure if these instructions should be removed, or pgxn should be updated?

**Comment by strk** [comment]
I guess we want to upload a new version.
@palmerj I registered a PGXN account `strk` if you want to delegate this part.

**Comment by strk** [comment]
@imincik I'm thinking that PGXN support more distribution than the LINZ PPA, as it seems to be *building* the package locally. So it might still be worth keeping, as long as we can handle to maintain it.

What I understand is that each extension has a single maintainer on PGXN so the only way to get this moved would be for @palmerj to delegate maintainance (to an "abstract" user?)

**Comment by imincik** [comment]
> @imincik I'm thinking that PGXN support more distribution than the LINZ PPA

I am not sure if we have enough force to maintain and support PGXN packages.

**Comment by strk** [comment]
Then I'd drop the `Easy Installation method` section.
Please confirm you're fine with it: #55 and #56

**Comment by imincik** [comment]
Today we discussed with @strk whether we should keep packages on PGXN or not.

Pros:
* support for other OS (Windows, Mac)

Cons:
* we don't have resources, test and dev environments and maybe even skills to support PostgreSQL on other OS than Linux
* for Debian/Ubuntu systems, installation even from self built DEB is better option

@palmerj , @dwsilk , @strk any thoughts ?

**Comment by dwsilk** [comment]
Dropping support for PGXN doesn't bother me.

**Comment by palmerj** [comment]
I more in favour of keeping in on PGXN, but agree the LINZ benefits are zero right now. Two pro reasons:

* access for other LINUX distros
* awareness that the extension exists for others PG users by putting it in a centralised index and website. I think the SEO for finding the extension by google is not enough.

I don't think the resources to publish are that great. On release just need to run one archive command and then upload to http://manager.pgxn.org.

My 2cents

**Comment by imincik** [comment]
@palmerj ,

My biggest concerns are that we are probably not able to test and support PGXN packages on other platforms right now.

For publishing to PGXN, we need access to your PGXN account or find some other workaround.

**Comment by palmerj** [comment]
> My biggest concerns are that we are probably not able to test and support PGXN packages on other platforms right now.

My experience is that support is little for *unix and auto builds and report from failure are done by the PXN people. Maybe just have a policy of saying sorry we can't help to Windows users? Of course your call.

**Comment by strk** [comment]
I think PGXN is useful, beside windows.
The only reason to drop would be if we cannot cope with
maintaining it.

Jeremy: the package is under your namespace, so nobody but you can
upload packages, so I think you should have the last word here.
Will you be willing to maintain it or find a way to share maintainance ?

**Comment by imincik** [comment]
My current opinion is that we definitely should not drop PGXN until we have proper Debian packages support at least for all supported Ubuntu LTS >= 14.04 (16.04 is missing now) and all supported PostgreSQL versions from apt.postgresql.org (this is missing as well because of Launchpad limits, we need to change whole DEB building pipeline to build packages for multiple PostgreSQL versions) in our Debian repository.

So keep PGXN for now.

**Comment by strk** [comment]
It looks like we don't need a publish the code for PGXN to grab it:
https://lists.osgeo.org/pipermail/postgis-devel/2017-October/026621.html

The only difference from publishing on PGXN.net is we need full URL and a known tag (if we want a non-development version)

**Comment by palmerj** [comment]
Ok thanks interesting and good for testing the meta.json file. However one of the main reasons in my mind is to add the extension to PGXN for good google SEO. Type "table versioning postgresql" into google and see what the top hit is :)

I wonder if it's possible to configure the PGXN account to point to a github branch rather than having to upload a release tarball.

**Comment by strk** [comment]
Interesting: google gives me the github page as first, and a competing technology
second (still on github): https://github.com/jasonk/postgresql-versioning
No mention of PGXS in the first page of results.

But I confirm PGXS is first from an untracked browser window !

PGXN code is here: https://github.com/pgxn/
Something similar to what you're asking is here:
https://github.com/pgxn/pgxn-manager/issues/47

**Comment by strk** [comment]
Now, in order to be able to fetch from repository we'd need a non-generated META.json, while we currently generate it at `make` time. If we plan to instruct users to PGXN directly from github, we should fix that too.

**Comment by strk** [comment]
I was wrong with the above, pgxnclient 1.2.1 can install from github repo and no META.json just fine, but older versions cannot install from http at all, looks like:  https://travis-ci.org/linz/linz-lds-bde-schema/jobs/285601161#L731-L733

**Comment by strk** [comment]
I'm taking it back, I've no evidence of old versions not working. Adding http based pgxn install in travis configuration for linz-lds-bde-schema here: https://github.com/linz/linz-lds-bde-schema/pull/49

**Comment by strk** [comment]
table_version 1.3.1 is now available on PGXN, so closin this. https://pgxn.org/dist/table_version/
