### ISSUE TITLE
Expensive revision table analyse call

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#34]
While profiling the enable of versioning I found that the `ANALYSE` call performed after creating the revision table takes 84% of the total time. This is true for the `bde.crs_adj_obs_change` table containing 100,148 rows. It takes 377 ms to *create* the revision table (basically copying all the data) and 1927 seconds to run `ANALYSE` on it.

This ticket is to evaluate whether we want to add an optional parameter to `ver_enable_versioning` to request skipping the `ANALYSE` call, so that callers can decide to postpone analysis to a separate (maybe background) job.

**Comment by strk** [comment]
1/4 of the total analyze time goes into analyzing the `proposed_status` column, which is a `character varying(4)` typed column, with this distribution:
```
 count | proposed_status 
-------+-----------------
    32 | DECM
   456 | PEND
 99660 | AUTH
(3 rows)
```

Analyzing that single column takes 510 ms, compared to 377 ms needed to *populate* the whole table !
This is with PostgreSQL 9.3.17

**Comment by strk** [comment]
This problem may be PostgreSQL version specific.
This is a comparison between ANALYSE on a single column and converting the whole table to JSON and counting characters of it. Queries are:
```
JSON: select sum(octet_length(row_to_json((a))::text)) from bde.crs_adj_obs_change a;
ANALYZE: analyze verbose bde.crs_adj_obs_change (proposed_status);
```

 - on PostgreSQL 9.6.3 I get: 549.524 ms for JSON and 37.212 ms for ANALYSE
 - on PostgreSQL 9.3.17 I get: 531.868 ms for JSON and 536.381 ms for ANALYSE

In both cases the default statistics target (as applied to the `proposed_status` column) is 500.

**Comment by strk** [comment]
- on PostgreSQL 9.4.9 I get: 1395.303 ms for JSON and 1325.912 ms for ANALYSE

Beside slower times (it's on another system, with slower disk) the times being comparable show that the ANALYZE improvement did not land in 9.4 yet.

**Comment by strk** [comment]
It's to be verified that `auto_explain` is able to print duration of analyze calls, or we need to find hot to better profile that.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by palmerj** [comment]
This task is still relevant.

**Comment by strk** [comment]
As we're running PostgreSQL 10 now, this should be tested there. And against a test database

**Comment by palmerj** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
I think analyse is expensive because we raise stats target of those
tables (but I could be wrong). Also IIRC I reported that newer
PostgreSQL had less of a problem with this.
