### ISSUE TITLE
Automate as much as possible generation of upgrade scripts

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#35]
Right now when you install `table_version` from master branch you end up with a `dev` version, and there's no way to upgrade it to another more recent changeset later.

This ticket is to setup some automatism to generate upgrade scripts.

**Comment by strk** [comment]
Moved here from #32

Right now all upgrade scripts are done manually, and are kept in the repository for every supported upgrade, even between old versions (ie: 1.0.0 to 1.0.1). And also when there's nothing to change (like in the 1.0.0 to 1.0.1 case). This allows upgrading from an older version to a newer one by multiple jumps. And allows to stop at an older version.

But it also result in code duplications.

Avoiding the duplication might be as easy as having the current SQL be generated by concatenating the initial state script with all subsequent upgrades. The code repository size would then be smaller than the current one, but the installed size of current script would be somewhat bigger. An advantage of that would be that you would be forced to generate a working upgrade, otherwise the CREATE EXTENSION call would just fail.

While the approach of getting to current by consecutively applying upgrades appeals me, I'm not sure how manageble it would be in the long run. For example the improvement in this PR would not go to the 15-table_diff_functions.sql file, but rather in a table_version--1.2.0--1.2.1.sql file, so when you need to look at a function definition you end up having to find out the current version looking in the upgrade scripts.

The alternative would be using some "adaptable upgrade" approach, where the code takes care of adding what's missing and dropping deprecated objects, if any. This is what PostGIS does, with the help of a perl scrip that extract various information from the official current SQL enabler script.

Which way do we want to go ?

**Comment by strk** [comment]
I've given automated upgrade a try in the PR adding `ver_version()` function, which clearly shows why it is useful to have automated upgrades. Seems to be not too complex in that it needs no external script to preprocess the SQL. Instead the code is tweaked to be idempotent.

Just some care needs be taken IF a type or table definition needs be updated, or a function signature needs to chage. But we can deal with that when and if that happens. Travis testing upgrades should help catching those cases. See #36

**Comment by imincik** [comment]
@strk , great job at the end. With combination of Travis tests it looks OK. Looks like a great improvement.
