### ISSUE TITLE
apply_table_diffs error

### ISSUE THREAD

**Issue by josephramsay** [linz/postgresql-tableversion#4]
Apply table diff function exception, citing null query string

********** Error **********

ERROR: Error executing template SQL: <NULL>
Error: query string argument of EXECUTE is null
SQL state: P0001
Context: SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
        CREATE TEMP TABLE table_diff AS
        SELECT
            T.id,
            T.action
        FROM
            table_version.ver_get_table_differences(
                '%1%', '%2%', '%3%'
            ) AS T (action CHAR(1), id %4%)
        ORDER BY
            T.action,
            T.id;
        $sql$,
        ARRAY[
            p_original_table::TEXT,
            p_new_table::TEXT,
            p_key_column::TEXT,
            table_version.ver_table_key_datatype(p_original_table, p_key_column)
        ]
    )"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_meshblock','admin_bdys_import.m_meshblock','code')"
PL/pgSQL function admin_bdys_import.import_admin_boundary(character varying) line 63 at EXECUTE statement

**Comment by palmerj** [comment]
Probably relates to this function not been tested for non integer primary keys. Will check out tomorrow

**Comment by josephramsay** [comment]
@palmerj explicitly added primary keys to the interim tables, which fixed this problem, thanks, but am now seeing the following more cryptic error message

********** Error **********

ERROR: invalid page in block 211 of relation base/141531030/11773
SQL state: XX001
Context: SQL statement "ANALYSE table_diff"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 32 at SQL statement
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_meshblock','admin_bdys_import.m_meshblock','code')"
PL/pgSQL function admin_bdys_import.import_admin_boundary(character varying) line 70 at EXECUTE statement

**Comment by palmerj** [comment]
Think that relates to a corrupt database. That's why it is corrupt. I will add a better user error message for the missing primary key.

**Comment by josephramsay** [comment]
@palmerj explicitly added primary keys to the interim tables, which fixed this problem, thanks, but am now seeing the following more cryptic error message

********** Error **********

ERROR: invalid page in block 211 of relation base/141531030/11773
SQL state: XX001
Context: SQL statement "ANALYSE table_diff"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 32 at SQL statement
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_meshblock','admin_bdys_import.m_meshblock','code')"
PL/pgSQL function admin_bdys_import.import_admin_boundary(character varying) line 70 at EXECUTE statement

**Comment by josephramsay** [comment]
Block 211 error did turn out to be a database corruption issue, 'fixed' by recreating affected tables and vacuuming.
