### ISSUE TITLE
Debian package only contains /usr/share/doc/postgresql-*-tableversion/

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#44]
I just realized that the debian packages do not contain the extension, but only the docs.
This ticket is to review package building and fix it for all versions of PostgreSQL.

See https://github.com/linz/linz-software-repository/wiki/Debian-packaging for a guide
and https://github.com/linz/postgresql-tableversion/pull/41 for the recent change adding packaging for more PostgreSQL versions.

**Comment by strk** [comment]
it is to be checked if the .deb files on the PPA are built correctly, and maybe add a Makefile rule to build them again (or at least fix .travis.yml recipe for package building tests)

**Comment by strk** [comment]
The README.md file also needs to be updated because as of https://github.com/linz/postgresql-tableversion/commit/965f441c2398f1032ff4991ecdeac0244949e64f it documents that packages are built with `dpkg-buildpackage -us -uc -b` but that command, from git, just doesn't work.

**Comment by imincik** [comment]
PPA builds should be fine, they are used for production.

**Comment by strk** [comment]
Yes, sorry, this ticket is just for the packages you obtain by following the instructions in the README file, which is what Travis does (see .travis.yml)

**Comment by imincik** [comment]
Packaging was broken after attempt to support multiple PostgreSQL versions. Should be fixed as part of #27

**Comment by strk** [comment]
`dpkg-buildpackage -us -uc -b` still fails in master due to #49 so I cannot test.
I filed #50 to fix that issue, will also automatically close this on merge.

**Comment by strk** [comment]
This is definitely fixed with recent `make deb` rule
