### ISSUE TITLE
Debian packaging of version 1.3.0

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#45]
See https://github.com/linz/postgresql-tableversion/releases/tag/1.3.0

Also see https://github.com/linz/postgresql-tableversion/issues/27 for multiple PostgreSQL versions
and https://github.com/linz/postgresql-tableversion/issues/44 to have Travis test generation of these packages.

**Comment by strk** [comment]
@imincik do you walso want to do this for this week ? Ideally by including #27

**Comment by imincik** [comment]
@strk ,

I did test package build on my machine. Following is content of built package. Please confirm that it looks OK:

```
drwxr-xr-x root/root         0 2017-09-19 03:34 ./
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/share/
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/share/doc/
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/share/doc/postgresql-9.3-tableversion/
-rw-r--r-- root/root       307 2017-09-19 03:33 ./usr/share/doc/postgresql-9.3-tableversion/changelog.Debian.gz
-rw-r--r-- root/root      1829 2017-09-19 03:33 ./usr/share/doc/postgresql-9.3-tableversion/copyright
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/share/doc/postgresql-doc-9.3/
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/share/doc/postgresql-doc-9.3/extension/
-rw-r--r-- root/root      6653 2017-09-19 03:34 ./usr/share/doc/postgresql-doc-9.3/extension/table_version.md.gz
-rw-r--r-- root/root       313 2017-09-19 03:34 ./usr/share/doc/postgresql-doc-9.3/extension/how_to_release.md
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/share/postgresql/
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/share/postgresql/9.3/
drwxr-xr-x root/root         0 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/
-rw-r--r-- root/root       541 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.1.0--1.1.1.sql
-rw-r--r-- root/root       541 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.1.1--1.1.2.sql
-rw-r--r-- root/root     57391 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.3.0.sql
-rw-r--r-- root/root     57391 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.3.0dev--1.3.0.sql
-rw-r--r-- root/root       105 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/version.sql
-rw-r--r-- root/root     57391 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.3.0next--1.3.0.sql
-rw-r--r-- root/root       184 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version.control
-rw-r--r-- root/root     57391 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.3.0--1.3.0next.sql
-rw-r--r-- root/root     40213 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.0.1--1.1.0.sql
-rw-r--r-- root/root      8443 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.1.2--1.1.3.sql
-rw-r--r-- root/root     57391 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.2.0--1.3.0.sql
-rw-r--r-- root/root       101 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/20-version.sql
-rw-r--r-- root/root      1759 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/META.json
-rw-r--r-- root/root      3675 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--unpackaged--1.0.1.sql
-rw-r--r-- root/root      9819 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.1.3--1.2.0.sql
-rw-r--r-- root/root       541 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/table_version--1.0.0--1.0.1.sql
```

**Comment by imincik** [comment]
@strk , are following files OK ? Is it downgrade support ?

```
./usr/share/postgresql/9.3/extension/table_version--1.3.0dev--1.3.0.sql
./usr/share/postgresql/9.3/extension/table_version--1.3.0next--1.3.0.sql
```

**Comment by strk** [comment]
On Mon, Sep 18, 2017 at 03:59:12PM +0000, Ivan Mincik wrote:
> @strk ,
> 
> I did test package build on my machine. Following is content of built package. Please confirm that it looks OK:
> 

[...]

> -rw-r--r-- root/root       105 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/version.sql

version.sql shuld probably not be here

> -rw-r--r-- root/root       101 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/20-version.sql

20-version.sql should probably not be here either

> -rw-r--r-- root/root      1759 2017-09-19 03:34 ./usr/share/postgresql/9.3/extension/META.json

Same for META.json, that target directory is not table_version
specific...

--strk;

**Comment by strk** [comment]
On Mon, Sep 18, 2017 at 09:00:49AM -0700, Ivan Mincik wrote:
> @strk , are following files OK ? Is it downgrade support ?
> 
> ```
> ./usr/share/postgresql/9.3/extension/table_version--1.3.0dev--1.3.0.sql
> ./usr/share/postgresql/9.3/extension/table_version--1.3.0next--1.3.0.sql
> ```

It's ok, all those files have the same content, is just a single
upgrade-safe script. They could theoretically all be symlinks or
hard links.

--strk;

**Comment by imincik** [comment]
Package uploaded for build to Launchpad - https://launchpad.net/~linz/+archive/ubuntu/test/+builds?build_state=pending  (requires Launchpad account)

**Comment by imincik** [comment]
postgresql-tableversion 1.3.0 was successfully built in PPA test branch `ppa:linz/test `. I want to test it before moving to `prod`

**Comment by strk** [comment]
I suggest we also have Travis recipes for public Linz components to test
these packages. Doing so requires putting the packages in a public PPA
repository.

**Comment by imincik** [comment]
My package tests are showing that current packaging wrong, fires:

* ./usr/share/postgresql/9.3/extension/META.json
* ./usr/share/postgresql/9.3/extension/20-version.sql
* ./usr/share/postgresql/9.3/extension/version.sql

can't be included in package. As you said above @strk . I need to fix it and upload packages again.

**Comment by strk** [comment]
@imincik those are now not included (both in `release-1.3` and `master` branches). I'm thinking to tag 1.3.1, for clean packaging, agreed ?

**Comment by imincik** [comment]
Fixes `1.3.1` package uploaded to `ppa:linz/test`.

**Comment by imincik** [comment]
Package looks OK, uploading to `ppa:linz/prod`

**Comment by imincik** [comment]
Uploaded to `ppa:linz-pub/pub` as well.

**Comment by strk** [comment]
time to update the testing bots to install table_version from PPA ?

**Comment by imincik** [comment]
Yes, it would be great to remove PGXN and installation from src
