### ISSUE TITLE
Make 1.3.0 packages available on PGXN

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#46]
Latest release on PGXN does not work against newer PostgreSQL versions, requiring workarounds in travis configuration for various clients (for example: https://github.com/linz/linz-lds-bde-schema/blob/9a05d52b401c01d6cee9baaa91f5335cbe6888d7/.travis.yml#L73)

This ticket is to upload a new version.

See also #45 and #30 

@palmerj I'll need permissions on PGXN to deal with this myself (I registered a `strk` account there)

**Comment by strk** [comment]
Closing as it was decided to abandon the PGXN maintainance. See https://github.com/linz/postgresql-tableversion/issues/30#issuecomment-331259849

**Comment by imincik** [comment]
@strk , let's wait for comments from others in https://github.com/linz/postgresql-tableversion/issues/30

**Comment by strk** [comment]
This PGXN issue from 2011 is about adding the possibility to have co-maintainers: https://github.com/pgxn/pgxn-manager/issues/6 -- I know it sounds crazy but... do you want me to give it a try ? :)

**Comment by palmerj** [comment]
I'll leave @imincik to decide.

In the mean time shall I reset my password and send you the credentials?

**Comment by strk** [comment]
> In the mean time shall I reset my password and send you the credentials? 

That'd help for sure.
I'll see if I can add a `make pgxn-publish` rule to simplify
this step in the future...

**Comment by palmerj** [comment]
On password sent :)

**Comment by imincik** [comment]
I think for now, using @palmerj credentials is the best way. @palmerj thanks.

**Comment by strk** [comment]
table_version 1.3.1 is now available on PGXN, and doc/howto_release.md was updated to mention this need

**Comment by palmerj** [comment]
Great thanks @strk
