### ISSUE TITLE
[travis fails] Error: debian/control needs updating from debian/control.in. Run 'pg_buildext updatecontrol'.

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#49]
Travis is failing since commit https://github.com/linz/postgresql-tableversion/commit/28629ca61c8bd91a77502041b72892086732f462 due to:
```
Error: debian/control needs updating from debian/control.in. Run 'pg_buildext updatecontrol'.
```

**Comment by strk** [comment]
This bug would be fixed by merging PR #50

**Comment by imincik** [comment]
@strk , as I said in #50 , `debain/control` file must be included in Git, this needs to be fixed.

**Comment by strk** [comment]
So `debian/control` is back in place, and travis is still happy. Closing.
