### ISSUE TITLE
Error calling table_version.ver_apply_table_differences(<table1>,<table2>,<id column>)

### ISSUE THREAD

**Issue by josephramsay** [linz/postgresql-tableversion#5]
I'm seeing an error with message "ERROR: type of parameter 26 (integer) does not match that when preparing the plan (character varying)" when running apply_table_differences().

The error doesn't occur when calling statements directly, only when called inside a function. See trace below. The Notices indicate the SQL being run.

Note. Column ordering is different between the two tables with the original having:
ogc_fid int, name varchar(100), shape geom(MP,4167)

and the import having columns:
ogc_fid int, shape geom, name varchar(100)

The function being called is here:
https://github.com/linz/download_ta_bdys/blob/admin_boundaries/aimsref_import.sql

Workflow is;
copy import table
do column matching
copy original table*
use apply_diffs() to update copied-original with copied-import
(* once we have this working the apply_diffs will be be run on the original itself)

------------------------------>8------------------------

NOTICE: 1.1 create table admin_bdys_import.m_statsnz_ta as select * from admin_bdys_import.temp_statsnz_ta
NOTICE: 1.2 alter table admin_bdys_import.m_statsnz_ta rename column geom to shape
NOTICE: 2.1 set search_path to admin_bdys,admin_bdys_import,public
NOTICE: 2.2 select addgeometrycolumn('m_statsnz_ta','temp',4167, 'MULTIPOLYGON', 2)
NOTICE: 2.3 update admin_bdys_import.m_statsnz_ta set temp = st_transform( st_setsrid(shape,4167),4167)
NOTICE: 2.4 alter table admin_bdys_import.m_statsnz_ta drop column shape
NOTICE: 2.5 alter table admin_bdys_import.m_statsnz_ta rename column temp to shape
NOTICE: 3.1 alter table admin_bdys_import.m_statsnz_ta drop column ta_code
NOTICE: 4.1 alter table admin_bdys_import.m_statsnz_ta add primary key (ogc_fid)
NOTICE: 5.1 create table admin_bdys_import.s_statsnz_ta as select * from admin_bdys.territorial_authority
NOTICE: 5.2 alter table admin_bdys_import.s_statsnz_ta add primary key (ogc_fid)
NOTICE: 5.3 select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')
NOTICE: Generating difference data for s_statsnz_ta
CONTEXT: SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement
ERROR: Error executing template SQL:
CREATE TEMP TABLE table_diff AS
SELECT
T.id,
T.action
FROM
table_version.ver_get_table_differences(
's_statsnz_ta', 'm_statsnz_ta', 'ogc_fid'
) AS T (action CHAR(1), id integer)
ORDER BY
T.action,
T.id;

Error: Failed comparing tables
PL/pgSQL function table_version.ver_get_table_differences(regclass,regclass,name) line 86 at IF
SQL statement "
CREATE TEMP TABLE table_diff AS
SELECT
T.id,
T.action
FROM
table_version.ver_get_table_differences(
's_statsnz_ta', 'm_statsnz_ta', 'ogc_fid'
) AS T (action CHAR(1), id integer)
ORDER BY
T.action,
T.id;
"
PL/pgSQL function table_version.ver_executetemplate(text,text[]) line 8 at EXECUTE statement
SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
CREATE TEMP TABLE table_diff AS
SELECT
T.id,
T.action
FROM
table_version.ver_get_table_differences(
'%1%', '%2%', '%3%'
) AS T (action CHAR(1), id %4%)
ORDER BY
T.action,
T.id;
$sql$,
ARRAY[
p_original_table::TEXT,
p_new_table::TEXT,
p_key_column::TEXT,
table_version.ver_table_key_datatype(p_original_table, p_key_column)
]
)"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement
ERROR: type of parameter 26 (integer) does not match that when preparing the plan (character varying)
CONTEXT: SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
CREATE TEMP TABLE table_diff AS
SELECT
T.id,
T.action
FROM
table_version.ver_get_table_differences(
'%1%', '%2%', '%3%'
) AS T (action CHAR(1), id %4%)
ORDER BY
T.action,
T.id;
$sql$,
ARRAY[
p_original_table::TEXT,
p_new_table::TEXT,
p_key_column::TEXT,
table_version.ver_table_key_datatype(p_original_table, p_key_column)
]
)"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement
********** Error **********

ERROR: Error executing template SQL:
CREATE TEMP TABLE table_diff AS
SELECT
T.id,
T.action
FROM
table_version.ver_get_table_differences(
's_statsnz_ta', 'm_statsnz_ta', 'ogc_fid'
) AS T (action CHAR(1), id integer)
ORDER BY
T.action,
T.id;

Error: Failed comparing tables
PL/pgSQL function table_version.ver_get_table_differences(regclass,regclass,name) line 86 at IF
SQL statement "
CREATE TEMP TABLE table_diff AS
SELECT
T.id,
T.action
FROM
table_version.ver_get_table_differences(
's_statsnz_ta', 'm_statsnz_ta', 'ogc_fid'
) AS T (action CHAR(1), id integer)
ORDER BY
T.action,
T.id;
"
PL/pgSQL function table_version.ver_executetemplate(text,text[]) line 8 at EXECUTE statement
SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
CREATE TEMP TABLE table_diff AS
SELECT
T.id,
T.action
FROM
table_version.ver_get_table_differences(
'%1%', '%2%', '%3%'
) AS T (action CHAR(1), id %4%)
ORDER BY
T.action,
T.id;
$sql$,
ARRAY[
p_original_table::TEXT,
p_new_table::TEXT,
p_key_column::TEXT,
table_version.ver_table_key_datatype(p_original_table, p_key_column)
]
)"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement
ERROR: type of parameter 26 (integer) does not match that when preparing the plan (character varying)
SQL state: P0001
Context: SQL statement "SELECT table_version.ver_ExecuteTemplate( $sql$
CREATE TEMP TABLE table_diff AS
SELECT
T.id,
T.action
FROM
table_version.ver_get_table_differences(
'%1%', '%2%', '%3%'
) AS T (action CHAR(1), id %4%)
ORDER BY
T.action,
T.id;
$sql$,
ARRAY[
p_original_table::TEXT,
p_new_table::TEXT,
p_key_column::TEXT,
table_version.ver_table_key_datatype(p_original_table, p_key_column)
]
)"
PL/pgSQL function table_version.ver_apply_table_differences(regclass,regclass,name) line 8 at PERFORM
SQL statement "select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid')"
PL/pgSQL function import_admin_boundary(character varying) line 137 at EXECUTE statement

**Comment by palmerj** [comment]
Hmm this is an interesting bug. We might have a edge case situation of cached plan record variable structure (v_table_record1 or v_table_record2), not having it's structure updated to the new datatype and failing a logical operator test.

I think this issue might be because multiple calls are being made to the ver_get_table_differences function with the first time being a VARCHAR primary key, then the second time being an INTEGER primary key - but can't be sure without a complete test case. At the moment I can't replicate the issue. 

@josephramsay: can you please give me a complete stand alone test case, which includes the data and the function call to get the error?

**Comment by josephramsay** [comment]
I'm running this on devassgeo01. The function is in linz_db.admin_bdys_import and called import_admin_boundary(name character varying).

The other tables don't seem to cause this error but calling the function select admin_bdys_import.import_admin_boundary('statsnz_ta') fails.

It takes a copy of the table admin_bdys.territorial_authority and attempts to compare/merge that with admin_bdys_import.temp_statsnz_ta

**Comment by palmerj** [comment]
@josephramsay I just called admin_bdys_import.import_admin_boundary('statsnz_ta') via pgadminIII  on the server and it didn't raise an error. Any ideas?

**Comment by josephramsay** [comment]
Thanks. Interesting. Maybe it's my setup then. I'll do some more testing and if it runs from psql -c we can probably consider it fixed.

**Comment by josephramsay** [comment]
Can confirm, function runs fine on commandline. Must be pgadmin (the older version of on my desktop anyway)

**Comment by josephramsay** [comment]
Spoke too soon, problem is intermittent. See this happening on command line and pgadmin for different tables including statsnz_ta and statsnz_meshblock
e.g.

select * from
table_version.ver_get_table_differences('admin_bdys_import.s_statsnz_ta', 'admin_bdys_import.m_statsnz_ta', 'ogc_fid') AS T (action CHAR(1), id integer)

ERROR:  Failed comparing tables
PL/pgSQL function table_version.ver_get_table_differences(regclass,regclass,name) line 86 at IF
ERROR: type of parameter 26 (integer) does not match that when preparing the plan (character varying)

**Comment by palmerj** [comment]
Hi Joe,

We are going to need a set of data (e.g pg_dump) and a set of steps used to generate the issue (e.g load  table is integer key, followed by table with varchar key etc etc), so I can replicate this. 

Also are your running the latest version of PG 9.3.13?

**Comment by josephramsay** [comment]
@palmerj its the PG instance running on devassgeo01:linz_db. Hard to replicate since its intermittent but with the current m/s_statsnz_ta tables all you need to run is;

select table_version.ver_apply_table_differences('admin_bdys_import.s_statsnz_ta','admin_bdys_import.m_statsnz_ta','ogc_fid');

**Comment by palmerj** [comment]
Can you please replicate this on your laptop please. We need the exact (e.g not run a couple of time) steps (incl data loading, sequence of SQL calls).

**Comment by josephramsay** [comment]
I can't replicate this exactly on my laptop since its running pg9.1 but I can demonstrate a test case that I think might be related:

```
drop table if exists test1a;
drop table if exists test1b;
create table test1a (id integer primary key,txt varchar);
insert into test1a values (1,'a');
insert into test1a values (2,'b');
insert into test1a values (3,'c');
create table test1b as select * from test1a;

drop table if exists test2a;
drop table if exists test2b;
create table test2a (id integer primary key,txt varchar);
insert into test2a values (1,'x');--change
insert into test2a values (2,'b');
insert into test2a values (4,'d');--add/delete
create table test2b as select * from test2a;

--create (succeeds)
select table_version.ver_apply_table_differences('test1a','test2a','id');
--create as (fails)
select table_version.ver_apply_table_differences('test1b','test2b','id');
```


For some reason t_v doesn't like tables created using "create T as select ..."

**Comment by josephramsay** [comment]
Have figured out a workaround, seems the problem was the OGR PostgreSQL driver i.e. In particular the ExecuteSQL() function. Switching to psycopg2 for the apply_table_differences() function on statsnz_ta tables fixes the problem.
