### ISSUE TITLE
Dropping and re-creating a versioned table does not affect its revisions

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#57]
Is it expected behavior that if you drop a table and re-create it it's still considered "versioned" ?
Because I think it's not really fully versioned (lacks triggers).

I think DROP/CREATE is a common behavior so there must be some kind of handling we want for it, but I was puzzled when DROP CASCADE a schema did not get me a clean schema on re-creating it (part of re-creating the schema is enabling table_versioning and that fails because the tables are "already versioned").

**Comment by dwsilk** [comment]
If this can be handled (aside from remembering to disable versioning every time you drop and re-enabling every time you re-create a table) then that would be awesome.

**Comment by palmerj** [comment]
> Is it expected behavior that if you drop a table and re-create it it's still considered "versioned" ?
Because I think it's not really fully versioned (lacks triggers).

No it's not, but at the time of development (PG 9.0), I could see a way to solve this problem, so users need to be careful not to call DROP CASCADE on versioned table without first calling table_version.ver_disable_versioning(). Note there is a dependancies created between the main table and the table_version version data table, so a DROP table DDL command will fail, so this at least provides some protection.

Since 9.3 there is now the ability to catch DDL event with triggers (https://www.postgresql.org/docs/9.3/static/sql-createeventtrigger.html), so this could be an option to solve this issue

**Comment by strk** [comment]
One way to handle this, I was thinking, could be to make
ver_is_versioned_table() return false unless table triggers
are also in place (and possibly suggest a function to call
to perform the cleanup records), and to make ver_enable_versioning()
add the missing pieces rather than skipping because table
is found to be "already versioned". Printing warnings would still
be good though...

**Comment by palmerj** [comment]
Yes those would be good changes as well as the trigger drop table catch

**Comment by strk** [comment]
I'm adding automated tests and also found that DROP TABLE CASCADE
still doesn't make is_table_versioned return false !

    DROP TABLE foo.dropme CASCADE;
    SELECT ok(NOT table_version.ver_is_table_versioned('foo', 'dropme'),
       'foo.dropme is not versioned after drop cascade');

Results in:

    ! not ok 80 - foo.dropme is not versioned after drop cascade

I'll give a stub at fixing this

**Comment by strk** [comment]
As per DDL triggers, right now table_version also supports
PostgreSQL-9.2, so if we add DDL we'd have to drop that support.

**Comment by palmerj** [comment]
Any reason to support 9.2 anymore?

**Comment by strk** [comment]
no reason to still support 9.2 from here, @imincik ?

As per my attempt to fix the problem it looks like `ver_is_versioned` is used by more internal code, like portions of `ver_enable_versioning` which would then fail if `ver_is_versioned` returned false on missing triggers. So it looks I should add an internal function with the old behavior for use internally..

**Comment by strk** [comment]
Please see #58 for a proposed handling of `ver_is_table_versioned`.

**Comment by imincik** [comment]
> Any reason to support 9.2 anymore?

No, please drop 9.2 if it helps.

**Comment by strk** [comment]
I think this was sorted out. Dropping versioned table effectively drops all its revisions. The only left-over are records in metadata tables, and PR #58 should take care of that. I wouldn't introduce DDL triggers yet.

**Comment by imincik** [comment]
Thanks @strk
