### ISSUE TITLE
Permission denied: ver_get_{schema_name}_{table_name}_diff()

### ISSUE THREAD

**Issue by dwsilk** [linz/postgresql-tableversion#6]
I want users to be able to call a function that checks the table_version schema for changes in their most recent revision. I have granted execute privileges to a group on a `ver_get_{schema_name}_{table_name}_diff()` function but it fails as `ver_expandtemplate` does not have the same privileges.

What is the best way to handle this? Grant the same privileges to `ver_expandtemplate` or should `ver_expandtemplate` use `SECURITY DEFINER` as some of the other functions do to enable all users to call it?

**Comment by palmerj** [comment]
@dwsilk: ver_ExecuteTemplate should have the public execution rights in the latest install. Your issue will probably be that ver_ExecuteTemplate is running a query on the revision table which the group role does not have the right to select on. We don't want to escalate privileges via SECURITY DEFINER on the general table version API functions as we have made a design decision to apply the permission controls at the table level and not to the function API level (except in few small cases revision triggers and creation and completion of revision session)

When the revisioning is enabled on the source table all the source table permissions are replicated (see of the https://github.com/linz/postgresql-tableversion/blob/master/sql/01-enable_versioning.sql#L80). So you have two options. Ensure the correct role permissions are on the source table before you enable revisoning, or manually add specific permissions to the revision table after enabling reversioning e.g:

```sql
GRANT SELECT ON TABLE table_version.{schema_name}_{table_name}_revision to XXXX;
```

**Comment by dwsilk** [comment]
Ah I see, yes, I was setting privileges after enabling versioning in the migration process. Will switch that around and confirm if it all works.

**Comment by dwsilk** [comment]
`TABLE table_version.{schema_name}_{table_name}_revision` now has the correct privileges but we are still getting the same error on the test server.

`ver_ExpandTemplate` has doesn't appear to have public execution rights.. it has
`REVOKE ALL ON FUNCTION table_version.ver_expandtemplate(text, text[]) FROM public;`

**Comment by palmerj** [comment]
What extension version is installed ?

**Comment by dwsilk** [comment]
`VERSION "1.1.3"`

**Comment by dwsilk** [comment]
`ver_create_revision` doesn't have public execution rights on the test server either. SECURITY DEFINER doesn't seem to be escalating rights there as I get permission denied on any role that isn't specifically granted execute privileges.

**Comment by dwsilk** [comment]
Fresh install of extension confirms no revocation of public execution rights, so likely some legacy privileges or manually executed privilege changes were causing the issue here.
