### ISSUE TITLE
Debian packaging of version 1.4.0

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#65]
See #64 (tag is ready)

**Comment by strk** [comment]
Ideally we'd want 2 different packages here:
  - postgresql-xx-tableversion
  - tableversion
The first would be the extension files (for `CREATE EXTENSION`) while the second would be the extension-less SQL scripts and the table_version-loader script.

See also https://github.com/linz/linz_bde_uploader/issues/141

**Comment by imincik** [comment]
@strk , I have no resources do split packaging in to 2 packages now. Is it OK to continue with what we have now ?

**Comment by strk** [comment]
Yes, no problem postponing the split.

**Comment by imincik** [comment]
Packages built and uploaded to Launchpad and Packagecloud test branches

**Comment by imincik** [comment]
Packages uploaded to Launchpad prod and pub and to Packagecloud prod as well.
