### ISSUE TITLE
Use pg_prove for testsuite

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#74]
Instead of pg_regress, we could use pg_prove, which is part of PgTap (already a dependency for testing).
Doing so would make adding tests easier (you don't need to update an "expected files" - see #73 for an example of such annoyance) and drop one bit of dependency from PostgreSQL package (#67 and #66)

**Comment by strk** [comment]
Example of switching to pg_prove: https://github.com/linz/linz-bde-schema/commit/10802c3d51cc5a4398c35b48952e354d473096a3

**Comment by palmerj** [comment]
Makes sense to me
