### ISSUE TITLE
Permission error for _changeset_revision

### ISSUE THREAD

**Issue by josephramsay** [linz/postgresql-tableversion#75]
Been trying to figure this one out, maybe somebody has an idea I hadn't thought of.

```
select table_version.ver_create_revision('some text');
select table_version.ver_apply_table_differences('admin_bdys.meshblock','admin_bdys_import.temp_meshblock','code');
select table_version.ver_complete_revision();
```

returns the error

```
ERROR: Error executing template SQL: 
        UPDATE admin_bdys.meshblock AS CUR
        SET shape = NEW_DAT.shape,code = NEW_DAT.code
        FROM admin_bdys_import.temp_meshblock AS NEW_DAT,
             table_diff AS INC
        WHERE INC.id = CUR.code 
        AND   NEW_DAT.code = CUR.code
        AND   INC.action = 'U'
        
Error: permission denied for relation _changeset_revision
```

This is only occurring on prd3/prd1. Same operation is fine on tst2/tst1. 
Have tried enable/disable versioning.

**Comment by strk** [comment]
Is this the same error reported in #21 ?

**Comment by josephramsay** [comment]
As discussed. 
The owner for **ver_create_revision/ver_complete_revision** is postgres with security definer but the function **ver_apply_table_differences** is postgres without security definer.  The **ver_apply_table_differences** function accesses **_changest_revision**.

**Comment by josephramsay** [comment]
Easy when you know what to look for. Seems the trigger function for the meshblock table was owned by the user so when updates triggered a change to **_changeset_revision** it was denied.

**Comment by strk** [comment]
so changing ownership of trigger function fixed it ?

**Comment by josephramsay** [comment]
Ran it overnight and it looks good this morning so I assume so yes. 
Other things I found:

1. table names for mesblock_concordance on prd2 were still in the old format
2. there was no proxy set on prd3
3. sequence index on prd1 revision table was out of sync
4. ownership wrong on table_version meshblock trigger function
