### ISSUE TITLE
Avoid table_version.revision reset on upgrade

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#77]
Sequence `table_version.revision` is forceably [being reset](https://github.com/linz/postgresql-tableversion/blob/master/sql/00-config_tables.sql#L25) on every upgrade.

Upgrade paths are autogenerated starting from version 1.3.0 so any database upgraded to 1.3.0, 1.3.1 or 1.4.0 would suffer from this problem.

See https://github.com/linz/ds-dev-team/issues/46

**Comment by palmerj** [comment]
But this sql script wouldn't run for an extension upgrade would It?

**Comment by palmerj** [comment]
Only the table_version--x.x.x--x.x.x.sql sql script

**Comment by strk** [comment]
Both extension-based and manual-based upgrades use the same files.
Upgrade files targetting 1.3.0 or higher are autogenerated, while upgrade to previous versions where done manually. Only the autogenerated upgrades are affected by the sequence reset.

Question: why is the sequence value being set at all ?

**Comment by strk** [comment]
Small test showing the problem:
```
CREATE EXTENSION table_version VERSION '1.2.0';
CREATE TABLE T (k int primary key, v text);
SELECT table_version.ver_enable_versioning('public', 't');


SELECT table_version.ver_create_revision('First revision');
SELECT table_version.ver_complete_revision();

ALTER EXTENSION table_version UPDATE TO '1.3.0';
SELECT table_version.ver_create_revision('Second revision');
```

The last line triggers:
```
psql:test_sequence_reset.sql:13: ERROR:  duplicate key value violates unique constraint "revision_pkey"
DETAIL:  Key (id)=(1001) already exists.
```

**Comment by palmerj** [comment]
> Question: why is the sequence value being set at all ?

Because there was a view that at some point a user might want to create from revisions prior to the first created revision. E.g historic bde. But maybe that was a bad idea and needs to be reciewed, also the API to create revisions before the first we never created so as it stands users would have to  complete manual insert of records

**Comment by palmerj** [comment]
> Both extension-based and manual-based upgrades use the same files.

Yes but I thought the schema creation scripts containing the sequence set are never called on upgrade. Obvoiusly not the case anymore looking at your test.

**Comment by strk** [comment]
The generated upgrade relies on the `CREATE OR REPLACE` and `CREATE IF NOT EXISTS` features. Kind of dangerous when you change the structure of something, but as long as tests coverage is acceptable it should be possible to find solutions to various problems.

**Comment by strk** [comment]
Upgrade was fixed in master branch, still has to be backported though

**Comment by palmerj** [comment]
Ok thanks @strk

**Comment by strk** [comment]
I've backported the fix to 1.3 branch (1.3.2) and 1.4 branch (1.4.1) - shall I tag & request packaging immediately or think of a way to add some automatic detection and handling of the corrupted sequence ? Something like checking if the `last_value` field of `table_version.version_id_seq` is smaller than `select max(id) from table_version.revision;` and in that case raise a WARNING and update the sequence ?

**Comment by strk** [comment]
Meanwhile I did implement a function checking for disordered revisions (based on `revision_time` order) and reorganization of it. It's to be tested more, discussion is in upstream ticket https://github.com/linz/ds-dev-team/issues/46#issuecomment-365974368

**Comment by strk** [comment]
I'm closing this as fixed, the tagging and packaging can wait for #87
