### ISSUE TITLE
Review ver_delete_revision function (warning message and documentation)

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#79]
Attempts to delete a still-referenced revision results in a message like this being printed as a WARNING:
```
WARNING:  Can not delete revision 1006 as it is referenced by other tables
```

That message is not detailed enough to know how to resolve the issue. For comparison, a direct DELETE, as issued by the `ver_delete_revision` function, gives this message:
```
ERROR:  update or delete on table "revision" violates foreign key constraint "tables_changed_revision_fkey" on table "tables_changed"
DETAIL:  Key (id)=(1006) is still referenced from table "tables_changed".
```

Which is far more instructive.

This said, beside telling more to the user, should `ver_delete_revision` function take care of cleaning up `tables_changed` records when deleting a revision ? Or os `ver_delete_revision` meant to only ever delete unused/empty revisions ?  [Documentation](https://github.com/linz/postgresql-tableversion/blob/1.4.0/doc/table_version.md#ver_delete_revision) is not clear (Related ticket:  https://github.com/linz/linz_bde_uploader/issues/151)

\cc @palmerj

**Comment by strk** [comment]
Ok then I think we should:
   1. Update documentation accordingly
   2. Improve the WARNING message

**Comment by palmerj** [comment]
Great I agree
