### ISSUE TITLE
ver_disable_versioning leaves stale record in table_version.versioned_tables

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#89]
@palmerj I just found that `table_version.ver_disable_versioning(schema, table)` leaves a record for `schema, table` in the `table_version.versioned_tables` table, is that by design ? Why would it be ?

A "funny" consequence of this is:
```
tv=# select table_version.ver_enable_versioning('public','t2');
t
tv=# select table_version.ver_disable_versioning('public','t2');
t
tv=# select table_version.ver_disable_versioning('public','t2');
WARNING:  Table public.t2 is known as versioned but lacks versioning triggers
HINT:  use ver_enable_versioniong to recover
ERROR:  Table public.t2 is not versioned
CONTEXT:  PL/pgSQL function ver_disable_versioning(name,name) line 4 at RAISE
tv=# 
```

Not the puzzling "is known as versioned" part of the warning message (which is due to presence of that schema,table pair in `table_version.versioned_tables`)

**Comment by palmerj** [comment]
> @palmerj I just found that table_version.ver_disable_versioning(schema, table) leaves a record for schema, table in the table_version.versioned_tables table, is that by design ? Why would it be ?

Originally there was an idea of disabling versioning (e.g APIs and triggers), but still still keeping the data. But that was never implemented and enable versioning would need to logic to catch-up/validate the master table aligns with the old revision data. I would suggest removing this functionality all together an ensuring that the data within tables_changed and versioned_tables is deleted.

**Comment by strk** [comment]
Proposed change for cleanup in PR #94, please review

**Comment by palmerj** [comment]
Thanks @strk. PR good to merge
