### ISSUE TITLE
Releases 1.3.2 and 1.4.1

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#92]
Tag, package and pgxn upload.
Needed for the fix in #77 and the workaround function added there.

**Comment by strk** [comment]
Releases [1.3.2](https://github.com/linz/postgresql-tableversion/releases/tag/1.3.2) and [1.4.1](https://github.com/linz/postgresql-tableversion/releases/tag/1.4.1) tagged.

Next stop: Debian packages and PGXN upload

@imincik can you do the debian packaging ? I'll do the PGXN part

**Comment by strk** [comment]
Version 1.4.1 uploaded to pgxn: 
https://manager.pgxn.org/distributions/table_version/1.4.1
The platform won't let me release 1.3.2 as the last one was 1.4.0 and releasing an earlier version is forbidden.

So only thing left to do here is debian packages

**Comment by imincik** [comment]
@strk of course I will do Debian packages

**Comment by imincik** [comment]
@strk , packaging of 1.3.2 also doesn't make a sense, because repository will override older version with newer one

**Comment by imincik** [comment]
Packages for Trusty and Xenial pushed to repo
