### ISSUE TITLE
Review SECURITY DEFINER settings

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#98]
It looks like some but not all functions are SECURITY DEFINER, in particular there's a need to write into `pg_depend` which is not guaranteed in some case. See https://github.com/linz/linz-bde-schema/pull/91#issuecomment-376821336

\cc @palmerj

**Comment by strk** [comment]
The function writing into pg_depend is `ver_enable_versioning` and is indeed NOT a security definer. Shouldn't it be ?

**Comment by strk** [comment]
For comparison, `ver_create_revision` is a SECURITY DEFINER.

**Comment by strk** [comment]
@palmerj the SECURITY DEFINER bit was removed from many functions by you on Feb 2016 via 1689aa657591123b3af70bc80ac5d98c8260005d -- do you remember why ?

**Comment by strk** [comment]
The drop of SECURITY DEFINERs was first published version 1.1.0 - 2016-03-23

**Comment by strk** [comment]
Current model is as follows:

 - Anyone can create and complete revisions (even a different user than the one who crated the revision can complete it)
 - Only those who have ownership privileges on a table can enable/disable versioning of such table
 - Only the owner of table_version extension can _delete_ an unused revision

Note that disabling versioning on a table results in all history for that table being deleted.

I guess I could write the above in the doc/table_version.md file to complete this task ?

**Comment by palmerj** [comment]
The model seems good. Yes please document it.

**Comment by strk** [comment]
I've added security model documentation as part of PR #137
