### ISSUE TITLE
Triggers on versioned tables should NOT be owned by table owner

### ISSUE THREAD

**Issue by strk** [linz/postgresql-tableversion#99]
Currently the trigger function added to tables by `ver_enable_versioning`
(via `ver_create_version_trigger`) is changed to be owned by the owner of the table being versioned, and are set to be SECURITY DEFINER. This means they will run with the permissions of the original table owner.

But this trigger function will want to write into `table_version.tables_changed`, and to read from the temporary `_changeset_revision`table. Both these operations are to be protected so we do not really want them to be granted to any user of `table_version` extension.

Rather, I think we want all  table_version related functions to run with the permission of some privileged role, probably to whoever issued the `CREATE EXTENSION` in the first place.

This ticket is to STOP altering the trigger functions so that they are owned by table owner.

This issue was found as part of reviewing security definer functions (#98) and hit on the road while adding `table_version` usage testing in linz-bde-schema (https://github.com/linz/linz-bde-schema/pull/91#issuecomment-376855086)

Note that if we change this ownership of triggers we'll need a way to change ownership back for pre-existing triggers.

@palmerj do you agree with the above plan ?

**Comment by imincik** [comment]
I understand this idea, it makes a sense for me, but I am afraid of such change in production.

**Comment by strk** [comment]
Which roles in production owns the `table_version.tables_changed` table ? Which role owns the BDE and LDS tables ? Which role runs the BDE updates (create_revision, INSERT, complete_revision...) ?

Before this change the revision triggers will be owned by the owner of the table being versioned. After this change the trigger will be owned by whoever called `ver_create_version_trigger`, which is not supposed to be called directly but via functions which are now all SECURITY-DEFINER, which means the triggers will be owned by the definer of the table_version functions, supposedly the same owner of `table_version.tables_changed` (tipically a superuser).

**Comment by palmerj** [comment]
> Rather, I think we want all table_version related functions to run with the permission of some privileged role, probably to whoever issued the CREATE EXTENSION in the first place.
> 
> @palmerj do you agree with the above plan ?

Yes I agree this should be improved so the table_version.tables_changed, table_version.versioned_tables and table_version.revision are owned by the extension owner. Also any object that is created during the ver_enable_versioning function call should also be owned by the extension owner and be set with the SECURITY DEFINER flag so trigger calls are executed with the privileges of extension owner.

**Comment by palmerj** [comment]
> Which roles in production owns the table_version.tables_changed table ? Which role owns the BDE and LDS tables ? Which role runs the BDE updates (create_revision, INSERT, complete_revision...) ?

I think we should get an audit of this. We can then use this information to develop upgrade scripts and unit tests

**Comment by dwsilk** [comment]
> Which roles in production owns the table_version.tables_changed table ?

The same superuser role that owns the `table_version` extension.

> Which role owns the BDE and LDS tables ?

A different superuser role that is specific to `bde` (although not really specific, because it's still a superuser).

> Which role runs the BDE updates (create_revision, INSERT, complete_revision...) ?

I'm not sure for `bde`, but for `roads` it's just a user that has been granted a group role that gives them permission to `INSERT` into roads tables that runs these functions.

**Comment by dwsilk** [comment]
The trigger functions are currently owned by the superuser role that is specific to the `bde` (not the role that owns the `table_version` extension - it is, as you've explained above, instead it's the same role that owns the tables).

**Comment by imincik** [comment]
@dwsilk thanks for information

**Comment by palmerj** [comment]
I think we should still do an audit of ownership across prdassgeo01/02 and devassgeo01, tstassgeo01

**Comment by strk** [comment]
If downstream confirms the fix this might need to be backported to 1.4 branch (or some equivalent fix would need to be done, or we'll have to require 1.5.0 downstream)
